### PR TITLE
Add some exceptions for bsb-native

### PR DESCRIPTION
**Pull request by jaredly**
lol there's so much trailing whitespace in these files

Test Plan:
`make worldnative`

### CODE REVIEW

**Comment by bsansouci** [comment]
Hey @jaredly Thanks for contributing! This is awesome.
I just grepped `failwith` and saw a couple more inside `bsb_config_parse.ml` (I think for a lot of those you can use `Bsb_exception.config_error`.
There's also `bsb_helper_packer` and `bsb_helper_linker`.

The rest looks good!

**Comment by bsansouci** [comment]
Oh and before I merge could you run `make force-snapshotml` so we get the packed files updated?

**Comment by jaredly** [comment]
Ok, I'll do the rest in a separate PR. Just wanted to get this in to make sure I was doing it right

**Comment by bsansouci** [comment]
Thanks a lot! This is great :)

**Pull request merged**
