### PR TITLE
Update readme to replace matchenv with bs cond compilation

### PR DESCRIPTION
**Pull request by jchavarri**
Baby steps 😅  let me know if there's anything that could be improved :)

### CODE REVIEW

**Comment by bsansouci** [comment]
Wow this is great! Thanks a lot. 

Two little things:
- could you make it more explicit that it has to be in an ML file?
- could you add a bit about how you also need to prevent bsb-native from compiling each module to targets that it does not support. Like “Platform specific files (like `MyLibrary_native`) should be put inside a folder that is only built to the specific backend (here native for example). You can do that like:
```
“sources”: [{
  “dir”: “src”,
  “subdirs”: [{
    “dir”: “native”,
    “backend”: “native”
  }]
}]
```

Honestly that setup kinda sucks but we should probably document it well enough that people can use it. We’ll find something better and upgrade everyone later.

**Comment by kennetpostigo** [comment]
@bsansouci why not fork bucklescript docusaurus site and add in bsb-native docs in there so that later both can be sync'd up?

**Comment by jchavarri** [comment]
@bsansouci thanks! done 👍

**Comment by bsansouci** [comment]
Thanks for your contribution!

@kennetpostigo I've been trying to keep bsb-native as simple as possible so bsb and bsb-native stay basically interchangeable in some sense. So not having an official website to have lots of docs forces me to avoid having too many features and make them complicated.
That said, it's possible I'm reaching the limit of that. I'll think about it, thanks for suggestion.

**Pull request merged**
